name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: 💚 Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: 🧱 Install Dependencies
        run: npm ci
      - name: 📦 Bundle Application
        run: npm run package
      - name: 🧪 Run Tests
        uses: coactions/setup-xvfb@v1
        with:
          run: npm test
      - name: 🐛 Debug Build
        uses: stateful/vscode-server-action@v1
        if: failure()
        with:
          timeout: '120000'
